name: CI

on:
  pull_request:
    branches:
      - '**'

concurrency:
  group: ${{ github.head_ref }}
  cancel-in-progress: true

jobs:
    Test:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
              clean: true
              path: repo
          - name: Install gtest
            run: git clone -b release-1.12.0 https://github.com/google/googletest.git && mkdir googletest/build && cd googletest/build && cmake .. && make && sudo make install
          - name: Configure
            run: mkdir -p  repo/build && cd repo/build && cmake ..
          - name: Make
            run: cd repo/build && make
          - name: Test
            run: cd repo/build && ./tests

    Style:
        runs-on: ubuntu-latest

        steps:
          - name: Checkout
            uses: actions/checkout@v3
            with:
              fetch-depth: 0
              clean: true
              path: repo
          - name: Install uncrustify
            run: git clone -b uncrustify-0.71.0 https://github.com/uncrustify/uncrustify && mkdir uncrustify/build && cd uncrustify/build && cmake .. && make && sudo make install
          - name: Check style
            run: cd repo && find . -name \*.hpp -exec uncrustify -c .github/uncrustify.cfg --check  {} + && find . -name \*.cpp -exec uncrustify -c .github/uncrustify.cfg --check  {} +
